### ISSUE TITLE
Java issues

### ISSUE THREAD

**Issue by leon1davies** [MendixCap/MX--SFTP-Module#1]
Added to the module to my mendix application and get the following java errors when compiling

Hello

Added the SFTPConnection module but am getting the following java errors when compiling...anyone got any ideas?

 

Buildfile: C:\MENDIX PROJECTS\HRConnect-main_2\deployment\build_core.xml

compile:
    [javac] Compiling 20 source files to C:\MENDIX PROJECTS\HRConnect-main_2\deployment\run\bin
    [javac] C:\MENDIX PROJECTS\HRConnect-main_2\javasource\encryption\actions\GeneratePGPKeyRing.java:74: error: cannot find symbol
    [javac]         char pass[] = this.PrivateKey.getPassPhrase_Plain().toCharArray();
    [javac]                           ^
    [javac]   symbol: variable PrivateKey
    [javac] C:\MENDIX PROJECTS\HRConnect-main_2\javasource\encryption\actions\GeneratePGPKeyRing.java:75: error: cannot find symbol
    [javac]         PGPKeyRingGenerator krgen = generateKeyRingGenerator(this.PrivateKey.getEmailAddress(), pass);
    [javac]                                                                  ^
    [javac]   symbol: variable PrivateKey
    [javac] C:\MENDIX PROJECTS\HRConnect-main_2\javasource\encryption\actions\GeneratePGPKeyRing.java:91: error: cannot find symbol
    [javac]         Core.storeFileDocumentContent(getContext(), this.PublicKey.getMendixObject(), pubFilename, new FileInputStream(tempASC));
    [javac]                                                         ^
    [javac]   symbol: variable PublicKey
    [javac] C:\MENDIX PROJECTS\HRConnect-main_2\javasource\encryption\actions\GeneratePGPKeyRing.java:109: error: cannot find symbol
    [javac]         Core.storeFileDocumentContent(getContext(), this.PrivateKey.getMendixObject(), skrFilename, new FileInputStream(tempSKR));
    [javac]                                                         ^
    [javac]   symbol: variable PrivateKey
    [javac] 4 errors

BUILD FAILED
C:\MENDIX PROJECTS\HRConnect-main_2\deployment\build_core.xml:25: Compile failed; see the compiler error output for details.

Total time: 1 second

**Comment by diblaauw** [comment]
I believe Dennis fixed it in his pull. I merged his changes here.
